### ISSUE TITLE
no rows in results with vertica 7

### ISSUE THREAD

**Issue by charleshansen** [wvanbergen/vertica#19]
I've recently started a Rails project with a Vertica 7 database and I cannot get the vertica gem to return rows from queries.  Sample code:

``` rb
connection = Vertica.connect(host: "x.x.x.x", user: "username", password: "password", database: "databasename")
result = connection.query "SELECT * FROM mytable"
puts result.columns
puts result.rows
```

This will print out the correct column information, but the rows will always be an empty array, even if 'mytable' has data.  It is possible I am doing something wrong, but it seems pretty simple.  Digging around in the internals some, when the query ran, `Connection#write_message` wrote a reasonable message, but `Connection#read_message` only ever got header information back from the socket.

Is Vertica 7 expected to be supported soon?

I am currently using the jdbc driver in jRuby as a workaround, but would love to get back to MRI if possible.

**Comment by baumanj** [comment]
I had a similar issue. Just in case someone finds themselves in the same place, the answer for me was that I needed to issue a `COMMIT;` so that my inserted data didn't disappear at the end of my session.
