### ISSUE TITLE
Share protocol guide document

### ISSUE THREAD

**Issue by mnikhil-git** [wvanbergen/vertica#29]
Hi @wvanbergen 

thanks for such a wonderful work. Its useful

Would you be able to help point out the vertica protocol guide that you would have probably used to write the code for your reference? I am trying to debug few things, particularly be able to send more options from the client side while the connection is being established. Any help is appreciated.

thank you

**Comment by wvanbergen** [comment]
I don't have protocol documentation for Vertica. I've used [the Postgres protocol document](http://www.postgresql.org/docs/9.2/static/protocol.html), on which Vertica's protocol is based. After that it is just trial and error based on what works (most things) and what doesn't (prepared statements)
