### ISSUE TITLE
COPY FROM LOCAL, any clue?

### ISSUE THREAD

**Issue by sonots** [wvanbergen/vertica#33]
Hi, I want execute `COPY schema.table FROM LOCAL 'pathToFile'`. I tried to run with `query` and `copy` method, but I got an message like

```
Unhandled message: #<Vertica::Messages::Unknown:0x007fa47a1d3690 @message_id="F",
      @data="\u0000\u0001pathToFile\u0000\u0000\u0000">
```

I am willing to implement this, but I have no clue about vertica protocol now.
Could you tell me how to handle this? I could not find any resources about protocol.

**Comment by wvanbergen** [comment]
The protocol for `COPY FROM LOCAL` has not been implemented so this won't work. You can use `COPY FROM STDIN` instead (see README).

If you're interested in implementing `COPY FROM LOCAL`, feel free to submit pull requests. As far as I know this is not a documented feature though.

**Comment by sonots** [comment]
COPY FROM LOCAL `path` is documented > https://my.vertica.com/docs/7.1.x/HTML/Content/Authoring/AdministratorsGuide/BulkLoadCOPY/UsingCOPYAndCOPYLocal.htm

**Comment by wvanbergen** [comment]
Not how the protocol works.

**Comment by sonots** [comment]
Okay, you meant how the protocol works is not documented. Understand, thanks.
