### ISSUE TITLE
io_select: Timeout in read_bytes

### ISSUE THREAD

**Issue by ayashjorden** [wvanbergen/vertica#36]
Hi,
This library is awesome :) made my life very easy. thank you.

I'd like to understand something about io_select method when used in read_bytes.
I'm dumping a huge result-set (6GB of data) into Json, is it possible that the timeout exception is thrown while rows are streamed from Vertica to the client because it takes a long time to dump the table?
or
No rows are streamed and the client is just waiting for them until the timeout?

Thank you,
Yarden

**Comment by ayashjorden** [comment]
Its timing out waiting for 1st row.

I added timeout override in my script and its working.
Thank you

**Comment by wvanbergen** [comment]
yeah, Vertica first has to execute the query on the server end before it can start sending results. While it is doing that, not traffic will be sent over the wire, which means the client can time out.
