### ISSUE TITLE
Invalid quoting of DateTime and Time values

### ISSUE THREAD

**Issue by maxd** [wvanbergen/vertica#38]
Look at this [line](https://github.com/wvanbergen/vertica/blob/adf436e9fa619c1b1d713bdbb0ea16382790b5f9/lib/vertica.rb#L32). As you can see this code convert original value to string and cast to `timestamp` datatype.

I see the following problems:

1. It is loose information about timezone.
1. It is force Vertica to using system timezone. If I pass value in +0300 timezone, but system timezone was set to +0400 Vertica will write value in +0400 timezone to `timestamptz` column.

How about just convert date time values to ISO8601 (which is de facto standard for present date and time) and remove cast to `timestamp` datatype?

P.S. I am ready to provide PR if somebody review and approve it.

**Comment by wvanbergen** [comment]
This makes sense to me. 

- I am a bit afraid of breaking backwards compatibility though What happens when you provide a `timestamptz` value to a `timestamp` column? How does that compare to the current behavior?
- We should probably add some documentation around timestamps and how they are handled. This can be very confusing.

**Comment by maxd** [comment]
> What happens when you provide a `timestamptz` value to a `timestamp` column?

`... If a time zone is specified in the input it is silently ignored.` - from [here](https://my.vertica.com/docs/7.1.x/HTML/Content/Authoring/SQLReferenceManual/DataTypes/Date-Time/TIMESTAMP.htm)

> How does that compare to the current behavior?

It is equal to current behavior with `timestamp` column because `quote` silently ignored specified timezone.

> I am a bit afraid of breaking backwards compatibility

Seems like this is doesn't break backward compatibility (as explained above) but fix bug with `timestamptz` columns.

**Comment by wvanbergen** [comment]
:+1:, feel free to open up a pull requests, with some tests that check the new behavior is working as expected.

**Comment by wvanbergen** [comment]
Potentially relevant: https://github.com/wvanbergen/vertica/pull/35
