### ISSUE TITLE
RFE: Add header row for array row_style

### ISSUE THREAD

**Issue by adamdrewapps** [wvanbergen/vertica#39]
It would be great if array row_style could return an array of the column names alongside the array of results. I have an application that requires an array of arrays from the database. I would have been able to use row_style array, but I need the names of the columns as well, so I need to convert from hash to array myself. It isn't difficult, but it adds some server processing time per request, so it would be good to eliminate that.

Thanks for the great library!

**Comment by wvanbergen** [comment]
The `Vertica::Result` class has a `columns` accessor that will give you information about the columns in a result.
