### ISSUE TITLE
COPY - Retrun Detailed Result of the Opertaion

### ISSUE THREAD

**Issue by ayashjorden** [wvanbergen/vertica#40]
Hello,
How can I understand from the `Vertica::Result` object if the operation was successful or not?
Can it return the number of rows that were copied?

Thank you,
Yarden

**Comment by wvanbergen** [comment]
- Based on the parameters you give to the COPY query, it will succeed/fail based on the number of records it was not able to process.
- If the query fails, the library raises an exception.
- AFAIK, the library currently doesn't tell you how many records were successfully copied. This may be possible, I have never looked into it. It's unlikely I will work on this myself (I don't use Vertica anymore in my day job), but I will gladly accept pull requests that would add something here.
