### ISSUE TITLE
SSL change?

### ISSUE THREAD

**Issue by maxstudener** [wvanbergen/vertica#57]
I'm getting Vertica::Error::SSLNotSupported with 1.0.0 but was not in 0.11.* . I looked at the code and noticed that the bytes sent are different, is this intended? The key difference is in 0.11.* we were calling message_string on the request which did some processing.

Vertica::Protocol::SslRequest (1.0.*)
[80877103].pack('N')

Vertica::Messages::SslRequest (0.11.*)
message_string [80877103].pack('N')

**Comment by wvanbergen** [comment]
Fixed, and I changed CI so it will fail if SSL ever breaks again. Released as 1.0.1
