### ISSUE TITLE
Autocommit true not working

### ISSUE THREAD

**Issue by annasob** [wvanbergen/vertica#59]
When I configure my connection with autocommit: true I do not see Update queries being executed. I need to add commit to the end of each query. "Update x SET y = 1; commit;"

**Comment by wvanbergen** [comment]
That's something to take up with Vertica support.

The client can only tell the server it wants autocommit to be turned on, how it is handled is up to the server. The test suite of them gem ensures it works for INSERT statements: https://github.com/wvanbergen/vertica/blob/master/test/functional/functional_connection_test.rb#L133-L148
