### ISSUE TITLE
undefined method `<<' for nil:NilClass vertica-1.0.1/lib/vertica/query.rb:106:in `buffer_row'

### ISSUE THREAD

**Issue by sonots** [wvanbergen/vertica#63]
I got an error of the title with a query such as

```
SET SEARCH_PATH TO test;
SELECT
	DISTINCT
	currency_name AS label,
	currency AS value
FROM
	biz_mst_ex_rate_diva
ORDER BY
	value
```

Adding `puts message` at https://github.com/wvanbergen/vertica/blob/31e3dee645c49aabf0dc38ad17e161175439eb97/lib/vertica/query.rb#L56, I got followings

```
#<Vertica::Protocol::CommandComplete:0x007f34fc4771f0>
#<Vertica::Protocol::RowDescription:0x007f34fc476ea8>
#<Vertica::Protocol::ParameterStatus:0x007f34fc4764f8>
#<Vertica::Protocol::ParameterStatus:0x007f34fc476278>
#<Vertica::Protocol::ParameterStatus:0x007f34fc475ff8>
#<Vertica::Protocol::DataRow:0x007f34fc475da0>
#<Vertica::Protocol::DataRow:0x007f34fc475620>
#<Vertica::Protocol::DataRow:0x007f34fc474dd8>
#<Vertica::Protocol::DataRow:0x007f34fc4745b8>
#<Vertica::Protocol::DataRow:0x007f34fc467e30>
#<Vertica::Protocol::DataRow:0x007f34fc467688>
#<Vertica::Protocol::CommandComplete:0x007f34fc466f08>
#<Vertica::Protocol::ReadyForQuery:0x007f34fc466be8>
```

This shows `SET SEARCH_PATH` goes into `CommandComplete` before main query completes, and `@buffer` is reset to nil at https://github.com/wvanbergen/vertica/blob/31e3dee645c49aabf0dc38ad17e161175439eb97/lib/vertica/query.rb#L86.

**Comment by wvanbergen** [comment]
You are basically running two statements inside a single query. This is not _officially_ supported by this library, although in some other cases it does work.

Easiest workaround would to run both statements as separate queries (using the same connection).

- I am happy to support patches that would improve multi-statement queries. What we really need is expanded test coverage for these kinds of scenarios. Also, in some cases we may have the rethink the API interface.

**Comment by sonots** [comment]
Sent a patch #67 to reset `@buffer` with `[]`. With this patch, results of only the last statement are obtained if multiple statements are given.
