### ISSUE TITLE
Vertica::Error::UnknownTypeError Unknown type OID: 1701934185

### ISSUE THREAD

**Issue by sonots** [wvanbergen/vertica#64]
I got following errors:

```
Vertica::Error::UnknownTypeError Unknown type OID: 1701934185
   lib/vertica/data_type.rb:42:in `block in build'
```

for a query such as:

```
select d as "日付",AVG(reqtime) as avg_reqtime
from analytics_products.argus_production_access_log
where d >= '2017-03-01'
group by d
order by avg_reqtime desc
```

which contains multibyte column names.

**Comment by wvanbergen** [comment]
I am pretty sure this is a different problem that has nothing to do with the name of the column. It's a data type that the library is not aware of.

Can you print the CREATE TABLE statement for the table you're using? I think you may be using a new type for one of the fields in your table, most likely the `d` field.

**Comment by sonots** [comment]
It seemed that the reason we get the wierd data type is because the position computed at https://github.com/sonots/vertica/blob/1896786060529c222a0a628a3caee448a27b0aa3/lib/vertica/protocol/backend/row_description.rb#L24 for next field was wrong for multibytes. This problem was fixed by #65.

**Comment by sonots** [comment]
d is DATE column

**Comment by wvanbergen** [comment]
Ah OK, closing this in that case. Feel free to open an issue for any unknown OID you encounter.
