### ISSUE TITLE
DELETE query is not executing.

### ISSUE THREAD

**Issue by bhushangahire** [wvanbergen/vertica#75]
We are trying to run DELETE query using this gem but nothing is happening. It doesn't errors out but doesn't deletes the records.

Is this supported?
I am using connection.query to run the delete query. 

Let me know if I am missing anything.

**Comment by wvanbergen** [comment]
Are you COMMITing the result?

**Comment by bhushangahire** [comment]
How?

**Comment by wvanbergen** [comment]
`connection.query("COMMIT")`

**Comment by bhushangahire** [comment]
Ohh ok thanks will try that.

**Comment by wvanbergen** [comment]
Anyway. `DELETE` queries are supported. The client doesn't differentiate between between  queries: it simply sends them to the server. If you are not getting an error back, the issue is on your server end.
